// INNER JOIN

SELECT 
	USERS.ID, USERS.NAME, USERS.ROLE, USERS.STATUS, 
	CATEGORIES.CODE, CATEGORIES.NAME, CATEGORIES.DESCRIPTION
FROM USERS

INNER JOIN CATEGORIES ON USERS.ID = CATEGORIES.USER_ID

// LEFT JOIN 1 TABLE 

SELECT 
	USERS.ID, USERS.NAME, USERS.ROLE, USERS.STATUS, 
	CATEGORIES.CODE, CATEGORIES.NAME, CATEGORIES.DESCRIPTION
FROM USERS

LEFT JOIN CATEGORIES ON USERS.ID = CATEGORIES.USER_ID

// LEFT JOIN 2 TABLE

SELECT 
	USERS.ID, USERS.NAME, USERS.ROLE, USERS.STATUS, 
	CATEGORIES.CODE, CATEGORIES.NAME, CATEGORIES.DESCRIPTION,
	PRODUCTS.QTY, PRODUCTS.PRICE  
FROM USERS

LEFT JOIN CATEGORIES ON USERS.ID = CATEGORIES.USER_ID
LEFT JOIN PRODUCTS ON CATEGORIES.ID = PRODUCTS.CATEGORY_ID


// RIGHT JOIN 1 TABLE 

SELECT 
	USERS.ID, USERS.NAME, USERS.ROLE, USERS.STATUS, 
	CATEGORIES.CODE, CATEGORIES.NAME, CATEGORIES.DESCRIPTION
FROM USERS

RIGHT JOIN CATEGORIES ON USERS.ID = CATEGORIES.USER_ID


// FULL JOIN 

SELECT 
	USERS.ID, USERS.NAME, USERS.ROLE, USERS.STATUS, 
	CATEGORIES.CODE, CATEGORIES.NAME, CATEGORIES.DESCRIPTION
FROM USERS

LEFT JOIN CATEGORIES ON USERS.ID = CATEGORIES.USER_ID

UNION 

SELECT 
	USERS.ID, USERS.NAME, USERS.ROLE, USERS.STATUS, 
	CATEGORIES.CODE, CATEGORIES.NAME, CATEGORIES.DESCRIPTION
FROM USERS

RIGHT JOIN CATEGORIES ON USERS.ID = CATEGORIES.USER_ID

